Multicopter.class : Multicopter.java
	javac Multicopter.java

test: Multicopter.class
	java Multicopter

run: Multicopter.class
	java Multicopter

edit:
	vim Multicopter.java

clean:
	rm -f *.class *~
