# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/simon/UnrealEngine
GAMEPROJECTFILE =/home/simon/Documents/Unreal Projects/MulticopterSim/MulticopterSim.uproject

TARGETS = \
	MulticopterSim-Linux-Debug  \
	MulticopterSim-Linux-DebugGame  \
	MulticopterSim-Linux-Shipping  \
	MulticopterSim-Linux-Test  \
	MulticopterSim \
	MulticopterSimEditor-Linux-Debug  \
	MulticopterSimEditor-Linux-DebugGame  \
	MulticopterSimEditor-Linux-Shipping  \
	MulticopterSimEditor-Linux-Test  \
	MulticopterSimEditor \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Shipping  \
	BlankProgram-Linux-Test  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient-Linux-Test  \
	CrashReportClient \
	UnrealLaunchDaemon-Linux-Debug  \
	UnrealLaunchDaemon-Linux-DebugGame  \
	UnrealLaunchDaemon-Linux-Shipping  \
	UnrealLaunchDaemon-Linux-Test  \
	UnrealLaunchDaemon \
	DsymExporter-Linux-Debug  \
	DsymExporter-Linux-DebugGame  \
	DsymExporter-Linux-Shipping  \
	DsymExporter-Linux-Test  \
	DsymExporter \
	UE4EditorServices-Linux-Debug  \
	UE4EditorServices-Linux-DebugGame  \
	UE4EditorServices-Linux-Shipping  \
	UE4EditorServices-Linux-Test  \
	UE4EditorServices \
	UnrealAtoS-Linux-Debug  \
	UnrealAtoS-Linux-DebugGame  \
	UnrealAtoS-Linux-Shipping  \
	UnrealAtoS-Linux-Test  \
	UnrealAtoS \
	MayaLiveLinkPlugin2016-Linux-Debug  \
	MayaLiveLinkPlugin2016-Linux-DebugGame  \
	MayaLiveLinkPlugin2016-Linux-Shipping  \
	MayaLiveLinkPlugin2016-Linux-Test  \
	MayaLiveLinkPlugin2016 \
	MayaLiveLinkPlugin2017-Linux-Debug  \
	MayaLiveLinkPlugin2017-Linux-DebugGame  \
	MayaLiveLinkPlugin2017-Linux-Shipping  \
	MayaLiveLinkPlugin2017-Linux-Test  \
	MayaLiveLinkPlugin2017 \
	MayaLiveLinkPlugin2018-Linux-Debug  \
	MayaLiveLinkPlugin2018-Linux-DebugGame  \
	MayaLiveLinkPlugin2018-Linux-Shipping  \
	MayaLiveLinkPlugin2018-Linux-Test  \
	MayaLiveLinkPlugin2018 \
	MinidumpDiagnostics-Linux-Debug  \
	MinidumpDiagnostics-Linux-DebugGame  \
	MinidumpDiagnostics-Linux-Shipping  \
	MinidumpDiagnostics-Linux-Test  \
	MinidumpDiagnostics \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Shipping  \
	SlateViewer-Linux-Test  \
	SlateViewer \
	SymbolDebugger-Linux-Debug  \
	SymbolDebugger-Linux-DebugGame  \
	SymbolDebugger-Linux-Shipping  \
	SymbolDebugger-Linux-Test  \
	SymbolDebugger \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Shipping  \
	TestPAL-Linux-Test  \
	TestPAL \
	UnrealCEFSubProcess-Linux-Debug  \
	UnrealCEFSubProcess-Linux-DebugGame  \
	UnrealCEFSubProcess-Linux-Shipping  \
	UnrealCEFSubProcess-Linux-Test  \
	UnrealCEFSubProcess \
	UnrealFileServer-Linux-Debug  \
	UnrealFileServer-Linux-DebugGame  \
	UnrealFileServer-Linux-Shipping  \
	UnrealFileServer-Linux-Test  \
	UnrealFileServer \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Shipping  \
	UnrealPak-Linux-Test  \
	UnrealPak \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector \
	UnrealWatchdog-Linux-Debug  \
	UnrealWatchdog-Linux-DebugGame  \
	UnrealWatchdog-Linux-Shipping  \
	UnrealWatchdog-Linux-Test  \
	UnrealWatchdog \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame \
	UE4Client-Linux-Debug  \
	UE4Client-Linux-DebugGame  \
	UE4Client-Linux-Shipping  \
	UE4Client-Linux-Test  \
	UE4Client \
	UE4Editor-Linux-Debug  \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor-Linux-Test  \
	UE4Editor \
	UE4Game-Linux-Debug  \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game-Linux-Test  \
	UE4Game \
	UE4Server-Linux-Debug  \
	UE4Server-Linux-DebugGame  \
	UE4Server-Linux-Shipping  \
	UE4Server-Linux-Test  \
	UE4Server\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


MulticopterSim-Linux-Debug:
	 $(PROJECTBUILD) MulticopterSim Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSim-Linux-DebugGame:
	 $(PROJECTBUILD) MulticopterSim Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSim-Linux-Shipping:
	 $(PROJECTBUILD) MulticopterSim Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSim-Linux-Test:
	 $(PROJECTBUILD) MulticopterSim Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSim:
	 $(PROJECTBUILD) MulticopterSim Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSimEditor-Linux-Debug:
	 $(PROJECTBUILD) MulticopterSimEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSimEditor-Linux-DebugGame:
	 $(PROJECTBUILD) MulticopterSimEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSimEditor-Linux-Shipping:
	 $(PROJECTBUILD) MulticopterSimEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSimEditor-Linux-Test:
	 $(PROJECTBUILD) MulticopterSimEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MulticopterSimEditor:
	 $(PROJECTBUILD) MulticopterSimEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Debug:
	 $(BUILD) UnrealLaunchDaemon Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-DebugGame:
	 $(BUILD) UnrealLaunchDaemon Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Shipping:
	 $(BUILD) UnrealLaunchDaemon Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Test:
	 $(BUILD) UnrealLaunchDaemon Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon:
	 $(BUILD) UnrealLaunchDaemon Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Debug:
	 $(BUILD) DsymExporter Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-DebugGame:
	 $(BUILD) DsymExporter Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Shipping:
	 $(BUILD) DsymExporter Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Test:
	 $(BUILD) DsymExporter Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter:
	 $(BUILD) DsymExporter Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Debug:
	 $(BUILD) UE4EditorServices Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-DebugGame:
	 $(BUILD) UE4EditorServices Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Shipping:
	 $(BUILD) UE4EditorServices Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Test:
	 $(BUILD) UE4EditorServices Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices:
	 $(BUILD) UE4EditorServices Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Debug:
	 $(BUILD) UnrealAtoS Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-DebugGame:
	 $(BUILD) UnrealAtoS Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Shipping:
	 $(BUILD) UnrealAtoS Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Test:
	 $(BUILD) UnrealAtoS Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS:
	 $(BUILD) UnrealAtoS Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2016-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2016-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2016-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2016-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2016:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2017-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2017-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2017-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2017-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2017:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2018-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2018-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2018-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2018-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayaLiveLinkPlugin2018:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MinidumpDiagnostics-Linux-Debug:
	 $(BUILD) MinidumpDiagnostics Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

MinidumpDiagnostics-Linux-DebugGame:
	 $(BUILD) MinidumpDiagnostics Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MinidumpDiagnostics-Linux-Shipping:
	 $(BUILD) MinidumpDiagnostics Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MinidumpDiagnostics-Linux-Test:
	 $(BUILD) MinidumpDiagnostics Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

MinidumpDiagnostics:
	 $(BUILD) MinidumpDiagnostics Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymbolDebugger-Linux-Debug:
	 $(BUILD) SymbolDebugger Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymbolDebugger-Linux-DebugGame:
	 $(BUILD) SymbolDebugger Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymbolDebugger-Linux-Shipping:
	 $(BUILD) SymbolDebugger Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymbolDebugger-Linux-Test:
	 $(BUILD) SymbolDebugger Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymbolDebugger:
	 $(BUILD) SymbolDebugger Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Debug:
	 $(BUILD) UnrealCEFSubProcess Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-DebugGame:
	 $(BUILD) UnrealCEFSubProcess Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Shipping:
	 $(BUILD) UnrealCEFSubProcess Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Test:
	 $(BUILD) UnrealCEFSubProcess Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess:
	 $(BUILD) UnrealCEFSubProcess Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Debug:
	 $(BUILD) UnrealFileServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-DebugGame:
	 $(BUILD) UnrealFileServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Shipping:
	 $(BUILD) UnrealFileServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Test:
	 $(BUILD) UnrealFileServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer:
	 $(BUILD) UnrealFileServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealWatchdog-Linux-Debug:
	 $(BUILD) UnrealWatchdog Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealWatchdog-Linux-DebugGame:
	 $(BUILD) UnrealWatchdog Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealWatchdog-Linux-Shipping:
	 $(BUILD) UnrealWatchdog Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealWatchdog-Linux-Test:
	 $(BUILD) UnrealWatchdog Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealWatchdog:
	 $(BUILD) UnrealWatchdog Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Debug:
	 $(BUILD) UE4Client Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-DebugGame:
	 $(BUILD) UE4Client Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Shipping:
	 $(BUILD) UE4Client Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Test:
	 $(BUILD) UE4Client Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client:
	 $(BUILD) UE4Client Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Debug:
	 $(BUILD) UE4Editor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Test:
	 $(BUILD) UE4Editor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Debug:
	 $(BUILD) UE4Game Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Test:
	 $(BUILD) UE4Game Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Debug:
	 $(BUILD) UE4Server Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-DebugGame:
	 $(BUILD) UE4Server Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Shipping:
	 $(BUILD) UE4Server Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Test:
	 $(BUILD) UE4Server Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server:
	 $(BUILD) UE4Server Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /property:TargetFrameworkVersion=v4.5 /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
